databases:
  - name: rails_setup_workshops
    databaseName: rails_setup_workshops
    user: rails_setup_workshops

services:
  - type: web
    name: rails_setup_workshops
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_setup_workshops
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
